// Code generated by MockGen. DO NOT EDIT.
// Source: ../query_executor.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cqrs "github.com/reecerussell/go-cqrs/cqrs"
)

// MockQueryExecutor is a mock of QueryExecutor interface.
type MockQueryExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockQueryExecutorMockRecorder
}

// MockQueryExecutorMockRecorder is the mock recorder for MockQueryExecutor.
type MockQueryExecutorMockRecorder struct {
	mock *MockQueryExecutor
}

// NewMockQueryExecutor creates a new mock instance.
func NewMockQueryExecutor(ctrl *gomock.Controller) *MockQueryExecutor {
	mock := &MockQueryExecutor{ctrl: ctrl}
	mock.recorder = &MockQueryExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryExecutor) EXPECT() *MockQueryExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockQueryExecutor) Execute(ctx context.Context, q cqrs.Query) *cqrs.ExecuteResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, q)
	ret0, _ := ret[0].(*cqrs.ExecuteResult)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockQueryExecutorMockRecorder) Execute(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockQueryExecutor)(nil).Execute), ctx, q)
}
